#!/bin/bash

if [[ $1 -eq "4.8" ]]
then
	echo "Starting install for GCC 4.8.5"
	echo "WARNING: This will take 5+ hours."
	sudo apt update
	sudo apt upgrade
	cd ~
	wget https://ftpmirror.gnu.org/gcc/gcc-4.8.5/gcc-4.8.5.tar.gz
	tar xf gcc-4.8.5.tar.gz
	cd gcc-4.8.5
	contrib/download_prerequisites
	cd ~
	rm -rf build && mkdir build && cd build
	../gcc-4.8.5/configure -v --enable-languages=c,c++ --prefix=/usr/local/gcc-4.8.5 --program-suffix=-4.8.5 --with-arch=armv7 --with-fpu=vfp --with-float=hard --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
	cd ~/build/
	make -j 4
	sudo make install-strip	
fi

if [[ $1 -eq "4.6" ]]
then
	echo "Starting install for GCC 4.6.4"
	echo "WARNING: This will take 5+ hours."
	sudo apt update
	sudo apt upgrade
	cd ~
	wget https://ftpmirror.gnu.org/gcc/gcc-4.6.4/gcc-4.6.4.tar.gz
	tar xf gcc-4.6.4.tar.gz
	cd gcc-4.6.4
	contrib/download_prerequisites
	cd ~
	rm -rf build && mkdir build && cd build
	../gcc-4.6.4/configure -v --enable-languages=c,c++ --prefix=/usr/local/gcc-4.6.4 --program-suffix=-4.6.4 --with-arch=armv7 --with-fpu=vfp --with-float=hard --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
	cd ~/build/
	make -j 4
	sudo make install-strip	
fi

